
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost

development:
  <<: *default
  database: CronusWebsite_development

  
test:
  <<: *default
  database: CronusWebsite_test

production:
  <<: *default
  database: CronusWebsite_production
  username: cronuswebsite
  password: cronuswebsite
