
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost

development:
  <<: *default
  database: CronusWebsite_development
  username: cronuswebsite
  password: cronuswebsite


test:
  <<: *default
  database: CronusWebsite_test
  username: cronuswebsite
  password: cronuswebsite


production:
  <<: *default
  database: CronusWebsite_production
  username: cronuswebsite
  password: cronuswebsite
  secret_key_base: cronuswebsite
